item {
  id: 1
  name: 'el_bombasi'
}

item {
  id: 2
  name: 'bicak'
}

item {
  id: 3
  name: 'fuze rampasi'
}

item {
  id: 4
  name: 'gemi'
}

item {
  id: 5
  name: 'havan topu'
}

item {
  id: 6
  name: 'helikopter'
}

item {
  id: 7
  name: 'iha'
}

item {
  id: 8
  name: 'kompozit_baslik'
}

item {
  id: 9
  name: 'silah'
}

item {
  id: 10
  name: 'tank'
}

item {
  id: 11
  name: 'zirhli arac'
}
